"""Symmetry projection onto a one-dimensional irrep:  psi_G(s) = 1/|G| sum_g chi(g)^* psi(g^{-1} s).

Group elements are (site permutation, global spin flip) pairs. With a permutation p (p[i] = image
of site i), (g s)_{p[i]} = s_i, so g^{-1} s = s[p]. Characters chi(g) are complex phases.

Constructors: :meth:`SymmetryGroup.from_generators` closes a set of generators with their
characters (checking consistency), so translations (momentum), point groups and the spin flip are
combined in one call; :meth:`SymmetryGroup.cyclic` handles a single generator.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple

import jax
import jax.numpy as jnp
import numpy as np


@dataclass
class SymmetryGroup:
    perms: np.ndarray            # (n_g, N)
    flips: np.ndarray            # (n_g,) in {+1, -1}
    chars: np.ndarray            # (n_g,) complex

    @property
    def order(self) -> int:
        return len(self.perms)

    @property
    def N(self) -> int:
        return self.perms.shape[1]

    @staticmethod
    def trivial(N: int) -> "SymmetryGroup":
        return SymmetryGroup(np.arange(N)[None, :], np.array([1]), np.array([1.0 + 0j]))

    @staticmethod
    def spin_flip(N: int, char: complex = 1.0) -> "SymmetryGroup":
        return SymmetryGroup(np.arange(N)[None, :].repeat(2, 0), np.array([1, -1]), np.array([1.0 + 0j, complex(char)]))

    @staticmethod
    def cyclic(perm: np.ndarray, order: int, char_index: int = 0, flip: bool = False) -> "SymmetryGroup":
        """The cyclic group generated by one permutation (or the spin flip), character exp(2 pi i m k / order)."""
        N = len(perm)
        gen = (np.asarray(perm, dtype=int), -1 if flip else 1, np.exp(2j * np.pi * char_index / order))
        return SymmetryGroup.from_generators([gen], N)

    @staticmethod
    def from_generators(generators: Sequence[Tuple[np.ndarray, int, complex]], N: int, tol: float = 1e-9) -> "SymmetryGroup":
        """Close generators (perm, flip, char) into a group; raise if the characters are inconsistent."""
        ident = np.arange(N)
        elems: List[Tuple[np.ndarray, int, complex]] = [(ident, 1, 1.0 + 0j)]
        keys = {(tuple(ident), 1): 0}
        frontier = [0]
        while frontier:
            nxt = []
            for a in frontier:
                p, f, c = elems[a]
                for (q, g, d) in generators:
                    # product (q, g, d) . (p, f, c): first apply (p, f), then (q, g): site i -> q[p[i]]
                    r = np.asarray(q)[p]; h = g * f; e = d * c
                    key = (tuple(r), h)
                    if key in keys:
                        if abs(elems[keys[key]][2] - e) > tol:
                            raise ValueError("inconsistent characters: the generators do not define a 1D irrep")
                    else:
                        keys[key] = len(elems); elems.append((r, h, e)); nxt.append(keys[key])
            frontier = nxt
        return SymmetryGroup(np.stack([e[0] for e in elems]), np.array([e[1] for e in elems]),
                             np.array([e[2] for e in elems]))

    def times(self, other: "SymmetryGroup") -> "SymmetryGroup":
        """Direct product with another group (they must commute as permutations)."""
        gens = [(p, f, c) for p, f, c in zip(self.perms, self.flips, self.chars)]
        gens += [(p, f, c) for p, f, c in zip(other.perms, other.flips, other.chars)]
        return SymmetryGroup.from_generators(gens, self.N)

    # ------------------------------------------------------------------ application
    def apply_all(self, s: jnp.ndarray) -> jnp.ndarray:
        """All g^{-1} s for a batch s (B, N) -> (n_g, B, N)."""
        perms = jnp.asarray(self.perms); flips = jnp.asarray(self.flips, dtype=s.dtype)
        out = s[:, perms] * flips[None, :, None]
        return jnp.transpose(out, (1, 0, 2))

    def project(self, log_psi_all: jnp.ndarray) -> jnp.ndarray:
        """Combine log psi(g^{-1} s) of shape (n_g, B) into log psi_G(s), shape (B,) (stable complex log-sum-exp)."""
        w = jnp.log(jnp.conj(jnp.asarray(self.chars)) / self.order + 0j)
        x = log_psi_all + w[:, None]
        m = jnp.max(jnp.real(x), axis=0, keepdims=True)
        return jnp.log(jnp.sum(jnp.exp(x - m), axis=0)) + m[0]

    def check_group(self) -> bool:
        keys = {(tuple(p), int(f)) for p, f in zip(self.perms, self.flips)}
        for p, f in zip(self.perms, self.flips):
            for q, g in zip(self.perms, self.flips):
                if (tuple(q[p]), int(f * g)) not in keys:
                    return False
        return True


def translation_group(lattice, momentum_index: int = 0) -> SymmetryGroup:
    """All lattice translations with character exp(-i k . t) for the momentum ``lattice.momenta()[momentum_index]``."""
    k = lattice.momenta()[momentum_index]
    gens = []
    for a, t in enumerate(lattice.cells):
        if np.all(t == 0):
            continue
        phase = np.exp(-1j * (t @ lattice.vectors) @ k)
        gens.append((lattice.translations[a], 1, phase))
    return SymmetryGroup.from_generators(gens, lattice.N) if gens else SymmetryGroup.trivial(lattice.N)


def point_group(lattice, name: str, order: int, char_index: int = 0, spin_flip: Optional[int] = None) -> SymmetryGroup:
    """Cyclic point group generated by a preset operation (e.g. 'C6'), character exp(2 pi i m k / order), optional flip."""
    p = lattice.point_ops()[name]
    G = SymmetryGroup.cyclic(p, order, char_index)
    if spin_flip is not None:
        G = G.times(SymmetryGroup.spin_flip(lattice.N, spin_flip))
    return G
